# Generated by Django 5.1 on 2024-08-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(max_length=20)),
                ("date", models.DateTimeField(null=True)),
                ("time", models.TimeField(null=True)),
                ("image", models.TextField()),
            ],
        ),
    ]
