# Generated by Django 5.1 on 2024-08-30 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_classroom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="time",
        ),
    ]
